my_dict = {
	"save": "",
	"current_customer_id": "800000915",
	"title": "MR",
	"given_name": "Ridwan",
	"gb_full_name": "Md. Ridwan Mizan",
	"gb_short_name": "Mizan",
	"gender": "Male",
	"account_officer": "12",
	"second_officer": "12",
	"sector": "123",
	"target": "100",
	"nationality": "BD",
	"cb_sector_code": "321",
	"customer_status": "123",
	"etin": "true",
	"etin_no": "12345",
	"dob": "2020-08-24",
	"family_name": "Ridwan",
	"mnemonic": "800000915",
	"spouse_name": "Rashed",
	"father_name": "Md. Mizanur Rahman",
	"mother_name": "Roksana Akter",
	"company_reg_no": "00663",
	"marital_status": "Unmarried",
	"industry": "450",
	"residence_code": "BD",
	"language": "English",
	"sms": "true",
	"permanent_address": "Rabeya Manjil, Baburail No:01 (Last End Road)",
	"village": "West Deobough",
	"police_station": "Fatullah",
	"upazilla": "Narayanganj Sadar",
	"district": "Narayanganj",
	"post_code": "1400",
	"permanent_country": "BD",
	"telephone": "01620810044",
	"present_address": "Rabeya Manjil, Baburail No:01 (Last End Road)",
	"present_town": "Narayanganj Sadar",
	"present_postcode": "1400",
	"present_country": "BD",
	"phone_res": "01620810044",
	"phone_office": "01620810044",
	"mobile": "01620810044",
	"fax": "N/A",
	"email": "ridwanmizan@gmail.com",
	"communication_address": "Rabeya Manjil, Baburail No:01 (Last End Road)",
	"communication_village": "my village",
	"communication_police_station": "my station",
	"communication_upozila": "sadar",
	"communication_district": "n.ganj",
	"communication_post_code": "1400",
	"communication_country": "BD",
	"communication_telephone": "01620810044",
	"introducer_account": "12345",
	"introducer_name": "Mizanur Rahman",
	"branch_name": "Narayanganj",
	"introducer_fathers_name": "Abdur Rahid",
	"introducer_mothers_name": "Rabeya ",
	"introducer_spouce_name": "Nayon",
	"introducer_present_address": "Baburail",
	"introducer_permanent_address": "Baburail",
	"introducer_designation": "IoT Eng.",
	"legal_id_type1": "NID",
	"legal_id_issuing_authority1": "Bangladesh Govt.",
	"legal_id_number1": "2848919748",
	"legal_id_issue_date1": "2020-08-24",
	"legal_id_exp_date1": "2020-08-25",
	"relation_code": "48",
	"relation_customer": "mizan",
	"relation_customer_liability": "100",
	"residence_status": "Living with parents",
	"residence_type": "Independent House",
	"residence_since": "2020-08-24",
	"residence_value": "10000",
	"residence_amount": "10000",
	"communication_type": "phone",
	"confidential": "yes",
	"preferred_communication": "telephone",
	"internet_banking": "yes",
	"mobile_banking": "yes",
	"account_title": "RIDWAN MIZAN",
	"income_source": "JOB",
	"ac_opening_officer": "Unknown",
	"ac_opening_officer_designation": "Unknown",
	"beneficial_owner": "Not applicable",
	"reason_of_ac_open": "Savings",
	"visa_type": "No Visa",
	"visa_validity": "2020-08-25",
	"customer_occupation": "Work",
	"net_worth": "1 lac",
	"ac_opening_way": "direct",
	"expected_monthly_txn": "1",
	"expected_monthly_no_of_txn": "1",
	"expected_monthly_cash_txn": "6",
	"overall_risk_assessment": ">=14",
	"comments": "asdf",
	"address_verified": "No",
	"address_verification_process": "Manually",
	"politically_exposed": "No",
	"approve_from_snr_mgmt": "No",
	"wealth_source": "Job",
	"personal_customer_interview": "No",
	"info_updated_personally": "Yes",
	"customer_type": "INDIVIDUAL"
}

print(len(my_dict))
